    var ERRORAPPLICATION={
        "USER_NAME_PASSWORD_WRONG":"USER_NAME_PASSWORD_WRONG",
        "DRIVER_EXISTS":"DRIVER_EXISTS",
        "DRIVER_NOT_EXISTS":"DRIVER_NOT_EXISTS",
        "TRIP_NOT_EXISTS":"TRIP_NOT_EXISTS",
        "YOU_NOT_OWNER_TRIP":"YOU_NOT_OWNER_TRIP",
        "YOU_CANCELED_THIS_TRIP":"YOU_CANCELED_THIS_TRIP",
        "YOU_CAN_CATCH_THIS_TRIP":"YOU_CAN_CATCH_THIS_TRIP",
        "THE_TRIP_COMPLETED":"THE_TRIP_COMPLETED",
        "THE_TRIP_HAS_BEEN_ASSIGNED_TO_ANOTHER_ASSET":"THE_TRIP_HAS_BEEN_ASSIGNED_TO_ANOTHER_ASSET",
        "YOU_HAVE_NOT_COMPLETED_THE_PREVIOUS_TRIP":"YOU_HAVE_NOT_COMPLETED_THE_PREVIOUS_TRIP",
    }

    module.exports=ERRORAPPLICATION;